### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735908736

### CODE REVIEW

**Comment by bissenbay** [comment]
@fridex @harshad16 if this kind of repos doesn't have `.aicoe-ci.yaml`, do I need to add one?

**Comment by fridex** [comment]
> @fridex @harshad16 if this kind of repos doesn't have `.aicoe-ci.yaml`, do I need to add one?

Yes, please do so :+1:

**Comment by bissenbay** [comment]
> > @fridex @harshad16 if this kind of repos doesn't have `.aicoe-ci.yaml`, do I need to add one?
> 
> Yes, please do so

thanks, @harshad16 PTAL https://github.com/thoth-station/lab/pull/243/commits/395b5eb4e46c5a2d6d92c7d24a5aa305f4f03fd8

**Review by harshad16 — APPROVED** [review]
thanks :100:

**Pull request merged**
