### PR TITLE
Add check for CVE messages

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
> Should we add some "message unit producer" to have an ability to easily distinguish these? I can imaging other pipeline steps could produce a justification with "advisory" in it.

I didn't know about advisory, I thought usually we had a common structure for justifications, like type and message for all justifications. Can't we have a common structure for all?

**Comment by pacospace** [comment]
> Should we add some "message unit producer" to have an ability to easily distinguish these? I can imaging other pipeline steps could produce a justification with "advisory" in it.

I didn't know about advisory, I thought usually we had a common structure for justifications, like type and message for all justifications. Can't we have a common structure for all?

**Comment by fridex** [comment]
> > Should we add some "message unit producer" to have an ability to easily distinguish these? I can imaging other pipeline steps could produce a justification with "advisory" in it.
> 
> I didn't know about advisory, I thought usually we had a common structure for justifications, like type and message for all justifications. Can't we have a common structure for all? @fridex WDYT?

As of now, we have "type" and "message". The security sieve has also additional fields such as package affected and advisory. It would be good to unify the report and create a schema for it :+1:

**Comment by pacospace** [comment]
> > > Should we add some "message unit producer" to have an ability to easily distinguish these? I can imaging other pipeline steps could produce a justification with "advisory" in it.
> > 
> > 
> > I didn't know about advisory, I thought usually we had a common structure for justifications, like type and message for all justifications. Can't we have a common structure for all? @fridex WDYT?
> 
> As of now, we have "type" and "message" in all units. The security step has also additional fields such as package affected and advisory. It would be good to unify the report and create a schema for it

I didn't see `type` and `message` in justifications with cve that is why I made that modification, but yes we should unify report and schema based for all justifications.

**Pull request merged**
